### PR TITLE
adding fee to fix issue #249

### PR DESCRIPTION
**Pull request by michaelneale**
Addresses compliance with spec as per: https://github.com/TBD54566975/tbdex-js/issues/249

cc @thehenrytsai

### CODE REVIEW

**Review by jiyoontbd — APPROVED** [review]

**Review by thehenrytsai — APPROVED** [review]
🚀

**Comment by thehenrytsai** [comment]
Consider looking at https://github.com/TBD54566975/web5-js/pull/653/files#diff-3067268e04946afc99fcc6d204f22cc7105a282f106c6eda212a85d8dd3e5ba2 for the security audit error.

**Comment by michaelneale** [comment]
@thehenrytsai need some help - kind of cant work out the pnpm issues. Should we be using --no-frozen-lockfile for release builds and ci or not? and no idea what latest error is? (I ran pnpm install locally) - any ideas?

**Comment by thehenrytsai** [comment]
Hey @michaelneale, investigated. Looks like `TbdexTestVectorsProtocol` tests that involves JSON parsing SOMETIMES take insane amount of time (~5 seconds per test) to complete causing test timeout failures. Glancing over the code however I don't see why it'd take milliseconds to complete sometimes and 10x or even 100x some other time.

Filed #252 to track this.

For now, the good ol rerun-until-success is a viable workaround.

**Pull request merged**
