### PR TITLE
Updated code and tests to align with latest `tbdex` main

### PR DESCRIPTION
**Pull request by thehenrytsai**
1. Updated `tbdex` submodule reference.
1. Updated code and tests to reflect Offering spec changes.
1. Updated code and tests to reflect RFQ spec changes.
1. Updated code and tests to reflect Quote spec changes.
1. Updated code and tests to reflect Order Status spec changes.
1. Fixed instructions for updating `tbdex` submodule in README.
1. Fixed tbDoc warnings.

### CODE REVIEW

**Review by jiyoontbd — APPROVED** [review]
woot!

**Review by michaelneale — APPROVED** [review]

**Comment by michaelneale** [comment]
nice one @thehenrytsai - any chance you could cast eyes over https://github.com/TBD54566975/tbdex-pfi-exemplar and https://github.com/TBD54566975/tbd-examples/tree/main/javascript/pfi-aud-usd-tbdex some time for any migration we may need to do?

**Comment by thehenrytsai** [comment]
@michaelneale, for sure! Will take a look next week after a bunch PRs currently waiting on me!

**Comment by thehenrytsai** [comment]
Thanks @jiyoontbd for reviewing (and keeping the spec + schema up-to-date in `tbdex` repo, making these changes a smooth sail!).

**Pull request merged**
